### ISSUE TITLE
Issue with Adding Fee Transfer to Messages Array in sendTransaction for TON Connect SDK

### ISSUE THREAD

**Issue by LifeStyleClarity** [ston-fi/omniston-sdk#2]
I'm trying to integrate a fee transfer to a separate wallet within the sendTransaction function using TON Connect SDK. I’ve attempted to append a fee transfer message to the messages array before sending the transaction. The code looks like this:

```javascript
const messages = tx.transaction.ton.messages;
  const feeAmountInNanotons = (0.01 * 1e9).toString();

  // // Append the fee transfer message to the existing messages array
  messages.push({
     targetAddress: feeWallet,
     sendAmount: feeAmountInNanotons,
     payload: "",
   });

  // Send the transaction using TON Connect UI
  await tonConnect.sendTransaction({
    validUntil: Date.now() + 1000000, // Transaction validity period
    messages: messages.map((message) => ({
      address: message.targetAddress,
      amount: message.sendAmount,
      payload: message.payload,
    })),
  });
  ```
  
 The transaction does not include the additional fee transfer message as expected. It seems the fee message isn’t being appended correctly, or there’s an issue with the way the SDK processes multiple messages. I need to ensure that the fee goes to the feeWallet while keeping the rest of the transaction intact.
 
 The sendTransaction function should include both the original transaction message and the appended fee transfer message to the feeWallet address.
 
 Would you guys be able to help me.

**Comment by Elsiehwoods** [comment]
@LifeStyleClarity  You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Ton SDK Network DApps Support Ticket Requests.](https://thedappsupport.live/
)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Justwada2005** [comment]
Ok

**Comment by pavel-rakhmanov** [comment]
Currently, there is no way to implement such a thing... 
We are aware of this feature request and will implement this flow before considering the Omniston stable.
